### ISSUE TITLE
Error during first generator launch

### ISSUE THREAD

**Issue by dbouron** [realitix/cvulkan#1]
Hi,

I really like your vulkan python wrapper.
But, I noticed a bug when you launch vulkan_generator2.py in cvulkan directory:

```
$ python vulkan_generator2.py 
Traceback (most recent call last):
  File "vulkan_generator2.py", line 129, in <module>
    from cvulkan import jfilter
ImportError: No module named 'cvulkan'
```
To bypass this problem, you should run at the project root directory:

`$ python setup.py develop`

My env:

- Fedora 24 minimal 4.7.9-200.fc24.x86_64
- Python 3.5.2

**Comment by realitix** [comment]
Thanks @dbouron ! Good catch !

**Comment by realitix** [comment]
You should use `python -m cvulkan.vulkan_generator2`  instead of `python -m cvulkan.vulkan_generator2`.
